### ISSUE TITLE
Where do the labs come from?

### ISSUE THREAD

**Issue by Haian-Jin** [Gogonemnem/visual-data-processing#1]
Hi, I found your finished assignments by accident when I browsed the github website. You did a good jod! 

And I found the labs seem to be well designed and I also wanted to finish these labs by myself. Could you please tell me where these labs are from? Is there any webside about the assignments or the course related to these assignments? 

Thanks for your attention.

**Comment by Gogonemnem** [comment]
Hi there, first of thank you for you compliments. I believe there were still some mistakes, though I do not remember them that closely. Second, the material is not publicly available, and I'm actually not sure if I may keep these notebooks online. These exercises came from the course Visual Data Processing from the minor course Computer Science at TU Delft.

I may private this repo (or even delete this repo), because I do not know if I may publicize these exercises. Anyhow, I will keep it up for at least a while though.

**Comment by Haian-Jin** [comment]
> Hi there, first of thank you for you compliments. I believe there were still some mistakes, though I do not remember them that closely. Second, the material is not publicly available, and I'm actually not sure if I may keep these notebooks online. These exercises came from the course Visual Data Processing from the minor course Computer Science at TU Delft.
> 
> I may private this repo (or even delete this repo), because I do not know if I may publicize these exercises. Anyhow, I will keep it up for at least a while though.

I know. Thanks again.
